Repository Developer-Student-Clubs-VSSUT-Burla/College-Comrade, pull requests merged in 2021-03, with the labels that each got.

#27 Added Splash Screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tt/SplashActivity.java
  app/src/main/res/font/alfa_slab_one.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/preloaded_fonts.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: GSSOC21, Level2

#26 Improve README.md
  README.md
Labels: GSSOC21, Level1

#38 add contributing.md
  CONTRIBUTING.md
Labels: GSSOC21, Level0

#49 Resolved Issue #47
  .idea/jarRepositories.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tt/MainActivity.java
Labels: GSSOC21, Level2

#40 Dashboard_changed
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/tt/PROFILE.java
  app/src/main/res/drawable/contact.jpg
  app/src/main/res/drawable/faculty.jpg
  app/src/main/res/drawable/holiday.jpg
  app/src/main/res/drawable/main_bg.xml
  app/src/main/res/drawable/notes.jpg
  app/src/main/res/drawable/syllabus.png
  app/src/main/res/drawable/timetable.jpg
  app/src/main/res/layout/activity_lecturenotes.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/values/colors.xml
Labels: GSSOC21, Level2

#60 Modified README.md
  README.md
Labels: GSSOC21, Level0

#55 contact us page
  .idea/codeStyles/Project.xml
  .idea/gradle.xml
  app/src/main/res/drawable/ic_waves.xml
  app/src/main/res/layout/activity_contact.xml
  app/src/main/res/values/strings.xml
Labels: GSSOC21, Level2

#70 [qa]:Add issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/general_issue.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GSSOC21, Level0
